apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: infrastructure
  name: localstack-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: infrastructure
  name: localstack-cfg
data:
  localstack.env: |
    SERVICES=s3,sqs,sns,ses,lambda
    DEFAULT_REGION=us-east-1
    DATA_DIR=/data/localstack
    DEBUG=1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: infrastructure
  name: localstack
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
        - name: localstack
          image: localstack/localstack:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4566
          envFrom:
            - configMapRef:
                name: localstack-cfg
          volumeMounts:
            - name: localstack-data
              mountPath: /data/localstack
          resources:
            limits:
              cpu: 1000m
              ephemeral-storage: 2Gi
              memory: 1024Mi
            requests:
              cpu: 250m
              ephemeral-storage: 1Gi
              memory: 256Mi
      volumes:
        - name: localstack-data
          persistentVolumeClaim:
            claimName: localstack-pvc

---
apiVersion: v1
kind: Service
metadata:
  namespace: infrastructure
  name: localstack-svc
spec:
  selector:
    app: localstack
  ports:
    - name: localstack
      port: 4566
  externalIPs:
    - 192.168.0.138
