apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: infrastructure
  name: zookeeper-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: infrastructure
  name: zookeeper-cfg
data:
  zoo.cfg: |-
    tickTime=2000
    dataDir=/data
    clientPort=2181
    initLimit=5
    syncLimit=2

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: infrastructure
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: zookeeper:3.8.1
          imagePullPolicy: Always
          ports:
            - name: client
              containerPort: 2181
          volumeMounts:
            - name: zookeeper-pvc
              mountPath: /data
            - name: zookeeper-cfg
              mountPath: /conf
          resources:
            limits:
              cpu: 500m
              ephemeral-storage: 1Gi
              memory: 1Gi
            requests:
              cpu: 250m
              ephemeral-storage: 1Gi
              memory: 512Mi
      volumes:
        - name: zookeeper-pvc
          persistentVolumeClaim:
            claimName: zookeeper-pvc
        - name: zookeeper-cfg
          configMap:
            name: zookeeper-cfg

---
apiVersion: v1
kind: Service
metadata:
  namespace: infrastructure
  name: zookeeper-svc
spec:
  externalIPs:
    - 192.168.0.138
  ports:
    - name: client
      port: 2181
  selector:
    app: zookeeper

