apiVersion: v1
kind: Secret
metadata:
  name: nodered-sct
type: Opaque
data:
  nodered-credential-secret: c2VjcmV0
  aws-access-key-id: a2V5
  aws-secret-access-key: c2VjcmV0
  db_password: bm9kZXJlZA==

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodered
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodered
  template:
    metadata:
      labels:
        app: nodered
    spec:
      containers:
        - name: nodered
          image: macedodosanjosmateus/nodered-poc:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
            requests:
              cpu: 500m
              memory: 256Mi
          ports:
            - containerPort: 1880
          env:
            - name: TZ
              value: America/Sao_Paulo
            - name: NODE_RED_ENABLE_SAFE_MODE
              value: "false"
            - name: NODE_RED_ENABLE_PROJECTS
              value: "true"
            - name: NODE_RED_CREDENTIAL_SECRET
              valueFrom:
                secretKeyRef:
                  name: nodered-sct
                  key: nodered-credential-secret
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: nodered-sct
                  key: aws-access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: nodered-sct
                  key: aws-secret-access-key
            - name: AWS_DEFAULT_REGION
              value: us-east-1
            - name: KAFKA_BROKERS
              value: kafka-svc.infra.svc.cluster.local:9092
            - name: KAFKA_TOPIC
              value: http.kafka.integration
            - name: AWS_QUEUE_URL
              value: http://localstack-svc.infra.svc.cluster.local:4566/000000000000/http-sqs-integration
            - name: POSTGRESQL_HOST
              value: postgres-svc.infra.svc.cluster.local
            - name: POSTGRESQL_PORT
              value: "5432"
            - name: NODE_RED_DB
              value: nodered_db
            - name: NODE_RED_DB_USER
              value: nodered
            - name: NODE_RED_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: nodered-sct
                  key: db_password

---
apiVersion: v1
kind: Service
metadata:
  name: nodered-svc
spec:
  type: ClusterIP
  selector:
    app: nodered
  ports:
    - name: nodered
      port: 1880
      targetPort: 1880

---
apiVersion: v1
kind: Service
metadata:
  name: nodered-lb-svc
spec:
  type: LoadBalancer
  selector:
    app: nodered
  ports:
    - name: nodered
      port: 1880
      targetPort: 1880

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodered-igs
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: nodered.cluster.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nodered-lb-svc
                port:
                  number: 1880
