apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: infrastructure
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: infrastructure
  name: mysql-cfg
data:
  MYSQL_DATABASE: sample_db
  MYSQL_USER: sample_user

---
apiVersion: v1
kind: Secret
metadata:
  namespace: infrastructure
  name: mysql-scr
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA==
  MYSQL_PASSWORD: c2FtcGxlX3Bhc3N3b3Jk

---
apiVersion: v1
kind: Service
metadata:
  namespace: infrastructure
  name: mysql-svc
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  externalIPs:
    - 192.168.0.138

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: infrastructure
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          envFrom:
            - configMapRef:
                name: mysql-cfg
            - secretRef:
                name: mysql-scr
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          resources:
            requests:
              memory: 64Mi
              cpu: 250m
            limits:
              memory: 128Mi
              cpu: 500m
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc
